# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]
  

jobs:
  build:

    runs-on: ubuntu-latest

    
    
    

    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js environment
      uses: actions/setup-node@v2-beta
      with:
        version:12
    - name: GitHub Action for Yarn
      uses: Borales/actions-yarn@v2.1.0 
      with:
        cmd: install 

    - name: creating build
      run: yarn build
      
    - name: installing surge
      run: sudo npm install -g surge
      
    - name: depoying surge
      run: surge ./build greenroes.surge.sh --token ${{secrets.REACT_SECRETS}}
